name: Build and Deploy
on:
  workflow_run:
    workflows: ['test.yml'] # 指定触发的 workflow 名称
    types:
      - completed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # 只有在 test.yml 通过后才执行
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

          # 缓存 pnpm 依赖
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 缓存构建产物
      - name: Cache dist folder
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ hashFiles('**/dumi.config.js') }}
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: Install and Build
        run: |
          npm i -g pnpm
          pnpm run init
          pnpm run build:doc
        env:
          NODE_OPTIONS: '--max_old_space_size=4096 --openssl-legacy-provider'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
